### PR TITLE
Fix RadecoFunction#call_sites

### PR DESCRIPTION
**Pull request by kriw**
The implementation of `RadecoFunction#call_sites` is fixed. (But `map` field is empty)
Also I have added a method `RadecoFunction#call_refs`.

### CODE REVIEW

**Comment by sushant94** [comment]
@kriw I'm sorry, but I think I missed it, can I know what this PR is for? What was the original bug and what is this trying to fix?

**Comment by HMPerson1** [comment]
I think you've misunderstood what `CallGraph` is; nodes *are* functions and edges *are* callsites/call-instructions.
I'm not entirely sure what `call_refs` is supposed to do but the vector it returns should always have a length of exactly one and that one value should always be `RadecoFunction.cgid`. A violation of either of these is (imho) a panic-worthy bug.

**Comment by HMPerson1** [comment]
If it helps, an example of how I used `CallGraph` is in [`fix_opcalls`](https://github.com/radare/radeco-lib/blob/9726e7db0245de2f973478aa19def9cab966de51/src/analysis/functions/fix_ssa_opcalls.rs#L28).

**Comment by kriw** [comment]
@HMPerson1 it helps. Thank you.

**Comment by kriw** [comment]
@sushant94 ping?
I will rebase #139 after you merge this PR.

**Pull request closed without merging**
