### PR TITLE
Print values in hex if value > 255

### PR DESCRIPTION
**Pull request by P4N74**
Solve the issue "numbers bigger than X should be in hexadecimal for redability" in https://github.com/radare/radeco/issues/7

### CODE REVIEW

**Comment by radare** [comment]
Looks good to me, but the tests are not passing, can you update them?

**Comment by P4N74** [comment]
Yeah, I will try look into it. However the two assert statement which were failing on my computer are https://github.com/radare/radeco-lib/blob/master/src/middle/phiplacement.rs#L69 and https://github.com/radare/radeco-lib/blob/master/src/middle/phiplacement.rs#L73 which I had commented out. Yesterday, on irc while neobrain and sushant were talking, sushant said that the assert statement at line 69 is actually an error which needs to be deleted out. And regarding the assert statement on line 73, I am not sure if that is supposed to pass or is that also an error in code. I will look into it. But for the assert statement on line 69, I think it should be deleted with commit message update phiplacement.rs

**Comment by sushant94** [comment]
@P4N74 Sorry it took me a while to reply to this. This PR seems good to me. Can you update it to have a "0x" prefix (or alternatively a 'h' suffix) when the value shown is in hex? Imo, this would make it much clearer as to which base the output is in.

**Comment by P4N74** [comment]
@sushant94 since I have added `{:#x}`, `#` here will prepend `0x` before outputting the hex values. Also I had verified that locally.

**Comment by sushant94** [comment]
Awesome, I didn't notice the '#'. sgtm. Merging if @radare is ok with this.

**Comment by P4N74** [comment]
sorry, i just accidentally updated my master without knowing that it would add to pull request :(

**Comment by crowell** [comment]
@sushant94, you can just squash it

On Mon, Mar 14, 2016 at 3:58 PM, Rakholiya Jenish <notifications@github.com>
wrote:

> sorry, i just accidentally updated my master without knowing that it would
> add to pull request :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radeco-lib/pull/26#issuecomment-196497495>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by P4N74** [comment]
or should i create a new fresh pull request from new branch and close this one?

**Comment by sushant94** [comment]
@P4N74 Don't worry about it, I'll cherry-pick the commit in.

**Comment by sushant94** [comment]
Merged in c99e7757384b67f586da4a1883c40d00fa882f5a. Thanks!

**Comment by radare** [comment]
👍

**Pull request closed without merging**
