### PR TITLE
My vsa

### PR DESCRIPTION
**Pull request by some-username**
I did some work on VSA. It is not by far where I want it to be, but I think its a base for future work. (And also I gained a lot of experience with radeco-lib.)
I do not expect this to be pulled anytime soon. I just want to make you aware of this work. (And am very interested in your comments - maybe I did something completely unneeded, maybe it's useful)

I will write here about what I definitely have to change soon.
I just really have to go to bed now.

### CODE REVIEW

**Comment by radare** [comment]
@sushant94 ^

**Comment by sushant94** [comment]
@some-username 
Hey! This looks great! It'll take me sometime to review. Can you give me a high level description of what works and what doesn't?

**Comment by some-username** [comment]
Currently, it does only relatively few things:
It is able to recover global/local a-locs (with a limitation, see below) and the contents of registers.
Currently, I assume uninitialised a-locs to be zero. This is ok for at least rsp. (Is there an easy way to get the contents of registers from SSA?)
This is a real problem for offsets of `rip`. Currently I am using the address of the current instruction, but as instructions have different lengths, this is not correct. (Hence in the example below, the load of the global var into the local var is not detected correctly.)

It does not handle branches (phi-funktions), yet.
Also the implementation of strided intervals is very rudimentary.
And there is no inter-procedual analysis, right now.

For examle
````
int global_var_I;
int global_var_II;

int main (void) {
        int local_var_I;
        int local_var_II;
        global_var_I = 31337;
        local_var_I = global_var_I;
        local_var_II = 42;
        global_var_II = local_var_II;
}
````
this is able to recover:
````
A_Loc { addr: MemAddr { region: MemRegion { region_type: Global }, offset: 2100088 }, size: None }
Strided Interval:
        mod: 0
        min: 31337
        max: 31337
A_Loc { addr: Reg { reg_name: "rsp" }, size: Some(64) }
Strided Interval:
        mod: 4
        min: -16
        max: 8
A_Loc { addr: MemAddr { region: MemRegion { region_type: Global }, offset: 2100067 }, size: None }
Strided Interval:
        mod: 0
        min: 42
        max: 42
A_Loc { addr: MemAddr { region: MemRegion { region_type: Local }, offset: -16 }, size: None }
Strided Interval:
        mod: 0
        min: 42
        max: 42
A_Loc { addr: MemAddr { region: MemRegion { region_type: Local }, offset: -8 }, size: None }
Strided Interval:
        mod: 0
        min: 0
        max: 0
A_Loc { addr: MemAddr { region: MemRegion { region_type: Local }, offset: -12 }, size: None }
Strided Interval:
        mod: 0
        min: 0
        max: 0
A_Loc { addr: Reg { reg_name: "rip" }, size: Some(64) }
Strided Interval:
        mod: 6
        min: 2100067
        max: 2100088
````
And yes, I need a better representation. :)
````

**Comment by XVilka** [comment]
Hi @some-username ! Awesome work, will add my comments as well in a couple days.

**Comment by some-username** [comment]
@XVilka Thanks!
Before you review, keep in mind that I'm actively changing (and planning to change) stuff.
Some of the planned changes are:
 - reorganizing code a little to be closer to the concept of "transformers" ("Analyzing Memory Accesses in x86 Executables" and other work by Gogul Balakrishnan and Thomas Reps et al.
 - change the strided interval to reflect uninitialized memory
 - more proper stack analysis (started with the stack size in the function analyzer FnAnalyzer) --- trying to recognize `push rbp` and `pop rbp` at beginning and end of functions
 - handling of phis will have to be done. Tbh, I haven't looked into that, yet.
 - something I probably have forgotten

Also I have to have a second look on the code myself. I think I have some duplicate code in there.
And keep in mind that I'm quite new to rust. I think I understood most basic concepts (I don't _know_ all) but applying them correctly is something completely different.
I would really appreciate hints.

**Comment by XVilka** [comment]
@some-username sorry, I didn't forgot you, just was a superbusy. Will try to check it the next week

**Comment by some-username** [comment]
I don't mind. I still have to contribute lots of improvements.
What I also encountered:
 - The current code can't handle loops. (So when you're executing it on something with a loop in it, it will overflow it's stack...)

I'm still quite busy with other things right now, so I hope to be able to contribute at the end of next week.

**Comment by XVilka** [comment]
@some-username as radare2 got accepted in GSoC - you can expect more activity here. If you're student - we'd love to see your application too.

**Comment by XVilka** [comment]
@some-username @sushant94 would be nice to merge this/decide what to do before GSoC starts.

**Comment by XVilka** [comment]
ping?

**Comment by some-username** [comment]
sorry, was busy lately.
Unfortunately I can not tell how soon I will have finished the stuff I wanted to do...

**Comment by XVilka** [comment]
@some-username btw, have you checked this, updated paper? I see you're referring to the old one. Here is a new one https://pdfs.semanticscholar.org/6ea6/dbd0cc8f41af69e3c30323869010a4fbee51.pdf

**Comment by XVilka** [comment]
And also this paper (Retypd) - https://arxiv.org/pdf/1603.05495.pdf - looks like the authors from the same company as previous article.

**Comment by some-username** [comment]
Oh, thanks for the hints. Will have a look at those.
Next up is probably some cleanup of my messy code...

**Comment by XVilka** [comment]
Just thought. What about supporting different VSA methods? Thus, naming will need to be changed. So in future we'll be able to choose which one suits better for the selected file.

**Comment by some-username** [comment]
Can you list what other VSA methods would be interesting and why?
Generally this sounds like a good Idea. I just would prioritize implementing *one* method properly right now.

**Comment by some-username** [comment]
In order to experiment with vsa, I changed minidec a little to accept binaries on the commandline and also enabled logging from within minidec. Those changes are not directly connected to vsa. Would it be ok to add it to this PR? (What would be an other, more proper way?)

**Comment by radare** [comment]
Yep thats fine

**Comment by XVilka** [comment]
@some-username I agree that we should focus on one VSA method first. But if you name it differently from just VSA, to be able to add other methods later (or during GSoC) - then I think we can merge your PR right after that. It's dangerous to keep PR big - see for example siol merging story. Other VSA methods can include one from Retypd, another from REWARDS, one more from Ramblr, etc...

**Comment by some-username** [comment]
Ok, I committed passing binaries as command line argument.
From my understanding calling minidec from r2 should still be possible. But when I try, I only get a different prompt - the way r2pipe works seems to have changed? Probably only the minidec/README.md needs to be changed?

**Comment by some-username** [comment]
@XVilka ok so what name(s) do you suggest to change? Probably the module. (analyzer-wysinwyx.rs?) What about structs, traits and function names?

**Comment by XVilka** [comment]
@some-username I think just module name. For now it's enough I think to prevent conflicts. We can think more if there will be more VSA implemented.

**Comment by XVilka** [comment]
@some-username also please rebase and I think we can merge after renaming.

**Comment by XVilka** [comment]
@some-username regarding minidec & r2pipe - I just tried yesterday everything was OK. Can you please describe your error more thoroughly?

**Comment by XVilka** [comment]
@some-username ping? Can you please rebase, rename the module and squash the changes? Then we'll merge it.

**Comment by some-username** [comment]
> regarding minidec & r2pipe - I just tried yesterday everything was OK. Can you please describe your error more thoroughly?

When I open r2 and type `#!pipe /path/to/minidec`, like the README.md suggests, I simply get another prompt (`>`).
Previously it was running the whole analysis.

**Comment by some-username** [comment]
I seem to have messed up rebasing/squashing quite a bit. (first time for me, was following https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request, after which I ended up with a messed up git repository...)

**Comment by some-username** [comment]
Still a mess but should be working, now.

**Comment by XVilka** [comment]
Uh. Yes, a bit mess. Will pick manually tomorrow.

**Comment by some-username** [comment]
I gave it another try. I think it is not clean in some places (regarding the non-vsa initial bug-fix) but in general it should be more sane. Please tell me if there's something to complain.

**Pull request merged**
