### PR TITLE
Race condition test patch

### PR DESCRIPTION
**Pull request by l4l**

### CODE REVIEW

**Comment by l4l** [comment]
Removed couple of tests, so there you can see the good looking travis
[Here](https://travis-ci.org/radare/radeco-lib/jobs/188347994#L1347) the problem test
if you launch few times `cargo test` you can see stuff like this:
screenshot- - --3-00 27 22-msk-2017

**Comment by l4l** [comment]
Backtrace leads to graph accessing: https://github.com/radare/radeco-lib/blob/master/src/middle/ssa/ssadot.rs#L101

**Comment by radare** [comment]
please rebase

**Comment by P4N74** [comment]
I don't think [this](https://github.com/radare/radeco-lib/pull/51/files#diff-2b692717a242330fd3fa92cc27056742R618 ) if statement is required now as the access to invalid node issue has been fixed in my previous pr (https://github.com/radare/radeco-lib/pull/62 and https://github.com/radare/radeco-lib/pull/63). Also [this](https://github.com/radare/radeco-lib/pull/51/files#diff-10aa2c91b0a19565e6dd6d1deb61c5c9R363) part won't be required too. This would just shadow over the actual problem in future.

**Comment by sushant94** [comment]
This was for #50 afair.

**Comment by XVilka** [comment]
Not actual anymore, thanks!

**Pull request closed without merging**
