### PR TITLE
Replace instruction pointer with address when used as an operand

### PR DESCRIPTION
**Pull request by kriw**
Added `op_length` argument in `process_op` and `length` in `process_in`.

[main_before.txt](https://github.com/radare/radeco-lib/files/1661452/main_before.txt)
[main_after.txt](https://github.com/radare/radeco-lib/files/1661453/main_after.txt)

### CODE REVIEW

**Comment by sushant94** [comment]
@kriw Seems good to me. I'll get back to this in the evening and merge :)

**Comment by kriw** [comment]
ping?

**Comment by sushant94** [comment]
@kriw Oops, sorry, been super busy lately. Most of the PR LGTM. However, could you add like an option to disable this? Meaning, add an option (`replace_rip` maybe?) to the `SSAConstructor`, and perform the replacement only if the `replace_rip` option is set.

**Comment by sushant94** [comment]
I was expecting something along the lines of what's done for [`assume_cc`](https://github.com/radare/radeco-lib/blob/master/src/frontend/ssaconstructor.rs#L55) in the SSAConstructor. This would allows us to toggle the `replace_rip` on/off as needed for the use-case.

**Comment by sushant94** [comment]
SGTM, merged.

**Pull request merged**
