### PR TITLE
Make accessing arguments for VarBindings.

### PR DESCRIPTION
**Pull request by megumish**
Implementation for accessing arguments in RadecoFunction.
Because I sent a pull request for the first time, it may be funny, but I'd like to make a review.

### CODE REVIEW

**Comment by megumish** [comment]
related to the issue #120

**Comment by sushant94** [comment]
@megumish Ok, this is a start. What we'd like to have are accesses to the underlying node data through the same interface, i.e., access node data for arguments (both mutably/immutably etc) and access their `ValueType` (again, mutably and immutably) and some tests showing this usage.

**Comment by megumish** [comment]
@suhant94 I understand as follows.

What we'd like to have are access not copy, but original.

And they may have mutability or imutability by each functions.

And then, this should not implement only arguments, but other `ValueType` (or called `BindingType`);e.g., RegistarLocal, StackLocal and so on.

Is this correct?

**Comment by sushant94** [comment]
@megumish I don't mean `BindingType`, but rather, `ValueType` from `middle::ssa::ssa_traits::ValueType` which can be accessed through `.node_data()` in `SSA` trait.

**Comment by megumish** [comment]
@sushant94 Ok, I get it. I'll implement some functions and tests related to it again.
I close this pullrequest.

**Pull request closed without merging**
