### PR TITLE
Fix panic

### PR DESCRIPTION
**Pull request by kriw**
Related to the issue #119 and PR #127 

Currently panics are fixed, but the emitted IRs are still incomplete.

TODOs are marked as `TODO`, `FIXME`.
Followings are the TODOs
* Implement unimplmented functions (e.g., RadecoFunction#locals, RadecoFunction#call_sites)
* Fix callfixer.rounded_analysis
* Produce correct SSA so as to pass verifier::verfy
* In WrappedR2Api, use generic type  instead of R2 of Rc<RefCell<R2>>

I would like to deal with above TODOs as other issues.

### CODE REVIEW

**Comment by sushant94** [comment]
@kriw This looks good to me. Do you intend to do the above TODOs on a separate PR so that this can be merged?

**Comment by XVilka** [comment]
Just don't forget about those, since there are many TODOs and a bunch of disabled code.

**Comment by kriw** [comment]
I was plannning to make issues and solve them as soon as possible.
Should I fix them on this PR or on separate PR?

**Comment by XVilka** [comment]
Can you please also rebase the PR?

**Comment by sushant94** [comment]
@kriw If this is ready for merge, please let me know. I'll review it once more and merge it in.

**Comment by kriw** [comment]
@sushant94 This is ready for merge.
Could you review it?

WrappedR2Api is not fixed now, I will work on it as another issue.

**Comment by sushant94** [comment]
SGTM, Merging. Thanks! @kriw: Open an issue to track `WrappedR2API` please.

**Pull request merged**
