### PR TITLE
Fixgraph

### PR DESCRIPTION
**Pull request by some-username**
fix usage of deprecated walk_edges_directed()

### CODE REVIEW

**Comment by sushant94** [comment]
Hey, the build is failing. You need to change the iterator for this to work.

**Comment by some-username** [comment]
Did have to run `cargo update` to run into this.
And until now, I still haven't figured out how to deal with the return value/type of the iterator.
I tried something like
`for edge in self.g.edges_directed(*n, EdgeDirection::Outgoing) {`
but in essence don't know how to extract the id from it.

**Comment by some-username** [comment]
I'm not quite sure about the last commit.
Before the code was matching on a ConstraintEdge. I wanted to reproduce this behaviour but was not able to match on the generic type of a struct. (I did not find out whether this is even possible.)
So the iterator returns something that looks like `EdgeReference<Ix = EdgeIndex<ConstraintEdge::EdgeIdx(i)>, _>`. I did not find out how to match on the generic types of `EdgeReference` and `EdgeIndex`.
This problem also occurs further down...

**Comment by some-username** [comment]
fixed the compiler errors, but one test is now failing. I need to check that the semantics stayed the same.

**Comment by smarek** [comment]
this is really appreciated, could you please fix the last conflict? thank you!

**Comment by some-username** [comment]
sorry that i was not very explicit.
i am aware of the conflict and aware that one testcase is failing, so i guess the semantic of my fix is a different than before. to resolve that i am currently reading the paper that was implemented and understand the algorithm.
i had a look at the merge conflict. it seems to be solvable trivially. but i am not quite sure about the desired way to resolve it. simply merge the master into the fixgraph branch?

**Comment by smarek** [comment]
yes, preferably, simply fix up fixgraph branch and that should affect this PR in being mergeable

**Comment by sushant94** [comment]
@some-username Hey, sorry I couldn't reply earlier. But here is something that you can refer to make these changes (same petgraph changes that I made in another repo): https://github.com/sushant94/libsmt.rs/commit/596a502ef7b4190c3bad7dd8e975f955c85c2558#diff-715b22b5b97eeb559e4c8148c710f6a2R105

Let me know if you can do that, otherwise I can handle it and merge this in for you :)

**Comment by some-username** [comment]
@sushant, thanks for the hint. that was useful.
i would like to try to do it. but right now, i have no time. so later today or tomorrow.

**Comment by some-username** [comment]
> yes, preferably, simply fix up fixgraph branch and that should affect this PR, and result in it being mergeable

the question was more on *how* to fixup the branch. i still have only few git experience, so i'm wondering whether to merge, branch or doing something completely different.

**Comment by some-username** [comment]
ok, i was a little impatient for the answer on how to fix the merge conflict, so i did a simple merge.

still i did not finish reading the TIE paper and there is still one test failing so i guess the semantics are not correct.
this is probably caused by the confusion whether the target or the source of an edge is/was used. (previously this was the .0 or .1 -notation, but i was not able to find what either was referring to when trying to search the petgraph history.)
i commented the places with respective TODOs.

**Comment by smarek** [comment]
Stacktrace of failed test is 
**env RUST_BACKTRACE=1 travis-cargo test**
```
---- backend::lang_c::c_simple::test::c_ast_basic_test stdout ----
	thread 'backend::lang_c::c_simple::test::c_ast_basic_test' panicked at 'not yet implemented', src/backend/lang_c/c_simple.rs:338
stack backtrace:
   1:     0x55cff12f13df - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:     0x55cff12f55dd - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:     0x55cff12f438d - std::panicking::default_hook::h0ac3811ec7cee78c
   4:     0x55cff12f4a88 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:     0x55cff10ad983 - std::panicking::begin_panic::h341b039f84d0b176
                        at /build/rustc-1.13.0+dfsg1/src/libstd/panicking.rs:413
   6:     0x55cff12688b2 - radeco_lib::backend::lang_c::c_simple::CAST::emit_c::h932924a1f281ae53
                        at /tmp/radeco-lib/src/backend/lang_c/c_simple.rs:338
   7:     0x55cff126cc70 - radeco_lib::backend::lang_c::c_simple::CAST::print::h76ebfe302366179e
                        at /tmp/radeco-lib/src/backend/lang_c/c_simple.rs:516
   8:     0x55cff126d412 - radeco_lib::backend::lang_c::c_simple::test::c_ast_basic_test::h654703ecf3b699b9
                        at /tmp/radeco-lib/src/backend/lang_c/c_simple.rs:538
   9:     0x55cff1297f4b - <F as alloc::boxed::FnBox<A>>::call_box::h141ef11b98b7e190
  10:     0x55cff1291443 - std::panicking::try::do_call::h2806fe336a468627
  11:     0x55cff12fcf36 - __rust_maybe_catch_panic
  12:     0x55cff12980f9 - <F as alloc::boxed::FnBox<A>>::call_box::h7fbe52e75ba03afb
  13:     0x55cff12f3250 - std::sys::thread::Thread::new::thread_start::h759e10bc4abc7e72
  14:     0x7f0efc516463 - start_thread
  15:     0x7f0efc0429de - __clone
  16:                0x0 - <unknown>


failures:
    backend::lang_c::c_simple::test::c_ast_basic_test

test result: FAILED. 35 passed; 1 failed; 0 ignored; 0 measured
```

Which means it fails under emit_c

**src/backend/lang_c/c_simple.rs (line 338)**:
```
CASTNode::FunctionHeader(_) => unimplemented!(),
```

Also don't worry with GIT, we can always squash your multiple commits into one, rewrite them or rebase them on top of the repository, if the branch **fixgraph** will compile and all tests pass in your env, then we can help you with proper git works.

**Comment by some-username** [comment]
Yes, I have seen that. And as the behavior differs from the behavior before my fix, I assume that I changed the semantics unfortunately I have only very little time right now. I hope I am able to commit something useful before monday.

**Comment by smarek** [comment]
W00t W00t ! Thank you @some-username

**Comment by some-username** [comment]
:D
I'm very glad myself. One of the first times to contribute to a project.
Let's continue. :)

**Comment by XVilka** [comment]
LGTM

**Comment by smarek** [comment]
Sincerely Radeco still does not compile, radeco-lib is ok, but dependencies in Radeco are not properly done. I've made my clone, in case anybody wants to test it out.

If you edit r2pm/db/radeco to fetch sources from https://github.com/smarek/radeco

Compile than fails like this:

```
> r2pm -i radeco
Processing radeco ...
Already up-to-date.
Install Done For radeco
    Updating git repository `https://github.com/radare/r2pipe.rs`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/smarek/radeco-lib`
    Updating git repository `https://github.com/radare/esil-rs`
       Fresh libc v0.2.17
       Fresh regex-syntax v0.3.9
       Fresh strsim v0.5.2
       Fresh esil v0.1.0 (https://github.com/radare/esil-rs#3a8375f6)
       Fresh log v0.3.6
       Fresh utf8-ranges v0.1.3
       Fresh winapi v0.2.8
       Fresh lazy_static v0.2.2
       Fresh ordermap v0.2.7
       Fresh rand v0.3.14
       Fresh fixedbitset v0.1.5
       Fresh rustc-serialize v0.3.21
       Fresh winapi-build v0.1.1
       Fresh num-traits v0.1.36
       Fresh petgraph v0.4.1
       Fresh r2pipe v0.4.0 (https://github.com/radare/r2pipe.rs#23018f83)
       Fresh num-integer v0.1.32
       Fresh num-complex v0.1.35
       Fresh memchr v0.1.11
       Fresh num-iter v0.1.32
       Fresh num-bigint v0.1.35
       Fresh aho-corasick v0.5.3
       Fresh kernel32-sys v0.2.2
       Fresh num-rational v0.1.35
       Fresh thread-id v2.0.0
       Fresh num v0.1.36
       Fresh thread_local v0.2.7
       Fresh regex v0.1.80
       Fresh docopt v0.6.86
       Fresh radeco-lib v0.1.0 (https://github.com/smarek/radeco-lib#960c3120)
   Compiling radeco v0.1.0 (file:///home/user/.config/radare2/r2pm/git/radeco)
     Running `rustc src/main.rs --crate-name radeco --crate-type bin -C codegen-units=4 -g --cfg feature=\"default\" --out-dir /home/user/.config/radare2/r2pm/git/radeco/target/debug --emit=dep-info,link -L dependency=/home/user/.config/radare2/r2pm/git/radeco/target/debug -L dependency=/home/user/.config/radare2/r2pm/git/radeco/target/debug/deps --extern r2pipe=/home/user/.config/radare2/r2pm/git/radeco/target/debug/deps/libr2pipe-7486d38511f6d9ac.rlib --extern rustc_serialize=/home/user/.config/radare2/r2pm/git/radeco/target/debug/deps/librustc_serialize-b495e2b03d862e12.rlib --extern log=/home/user/.config/radare2/r2pm/git/radeco/target/debug/deps/liblog-bf16bb9a4912b11d.rlib --extern docopt=/home/user/.config/radare2/r2pm/git/radeco/target/debug/deps/libdocopt-664aa2a6d9ccf7ca.rlib --extern radeco_lib=/home/user/.config/radare2/r2pm/git/radeco/target/debug/deps/libradeco_lib-05b2ae512aff3750.rlib`
error[E0432]: unresolved import `radeco_lib::utils::Analysis`
 --> src/structs.rs:6:25
  |
6 | use radeco_lib::utils::{Analysis, Pipeline, Pipeout, Runner};
  |                         ^^^^^^^^ no `Analysis` in `radeco_lib::utils`

error[E0432]: unresolved import `radeco_lib::utils::Pipeline`
 --> src/structs.rs:6:35
  |
6 | use radeco_lib::utils::{Analysis, Pipeline, Pipeout, Runner};
  |                                   ^^^^^^^^ no `Pipeline` in `radeco_lib::utils`

error[E0432]: unresolved import `radeco_lib::utils::Pipeout`
 --> src/structs.rs:6:45
  |
6 | use radeco_lib::utils::{Analysis, Pipeline, Pipeout, Runner};
  |                                             ^^^^^^^ no `Pipeout` in `radeco_lib::utils`

error[E0432]: unresolved import `radeco_lib::utils::Runner`
 --> src/structs.rs:6:54
  |
6 | use radeco_lib::utils::{Analysis, Pipeline, Pipeout, Runner};
  |                                                      ^^^^^^ no `Runner` in `radeco_lib::utils`

error[E0412]: type name `radeco_lib::utils::Runner` is undefined or not in scope
  --> src/args.rs:67:20
   |
67 |     runner: Option<radeco_lib::utils::Runner>,
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^ undefined or not in scope
   |
   = help: no candidates by the name of `Runner` found in your project; maybe you misspelled the name or forgot to import an external crate?

error: no method named `get_bin_info` found for type `r2pipe::R2` in the current scope
   --> src/structs.rs:102:31
    |
102 |             let bin_info = r2.get_bin_info().unwrap();
    |                               ^^^^^^^^^^^^

error: no method named `get_reg_info` found for type `r2pipe::R2` in the current scope
   --> src/structs.rs:198:24
    |
198 |             let r = r2.get_reg_info().ok();
    |                        ^^^^^^^^^^^^

error: the type of this value must be known in this context
  --> src/args.rs:89:12
   |
89 |         if runner.is_err() {
   |            ^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

error: Could not compile `radeco`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name radeco --crate-type bin -C codegen-units=4 -g --cfg feature="default" --out-dir /home/user/.config/radare2/r2pm/git/radeco/target/debug --emit=dep-info,link -L dependency=/home/user/.config/radare2/r2pm/git/radeco/target/debug -L dependency=/home/user/.config/radare2/r2pm/git/radeco/target/debug/deps --extern r2pipe=/home/user/.config/radare2/r2pm/git/radeco/target/debug/deps/libr2pipe-7486d38511f6d9ac.rlib --extern rustc_serialize=/home/user/.config/radare2/r2pm/git/radeco/target/debug/deps/librustc_serialize-b495e2b03d862e12.rlib --extern log=/home/user/.config/radare2/r2pm/git/radeco/target/debug/deps/liblog-bf16bb9a4912b11d.rlib --extern docopt=/home/user/.config/radare2/r2pm/git/radeco/target/debug/deps/libdocopt-664aa2a6d9ccf7ca.rlib --extern radeco_lib=/home/user/.config/radare2/r2pm/git/radeco/target/debug/deps/libradeco_lib-05b2ae512aff3750.rlib` (exit code: 101)
```

**Comment by XVilka** [comment]
Merged your work, thanks a lot! I hope you'll continue to contribute :)

**Comment by XVilka** [comment]
@smarek can you please open an issue in radeco instead of a lib. And yes, it's a known issue. Radeco (apart from the lib) should be rewritten almost completely.

**Pull request closed without merging**
